### ISSUE TITLE
Kirjete tabelisse persoonireale elukoht (pereregistrist raamatu_omavalitsus)

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/repis#13]
Hetkeseisu saab kontrollida 
``` sql
select *
from repis.kirjed k
left join import.pereregister p on p.isikukood = k.kirjekood
where k.Elukoht = ''
and p.raamatu_omavalitsus > '';
```

**Comment by mitselek** [comment]
kontrollida, kas on ehk juba tehtud

**Comment by UlleKr** [comment]
Kui on tehtud, tuleb sellest märku anda.

Kontakt Mihkel Putrinš ***@***.***>) kirjutas kuupäeval T,
23. aprill 2024 kell 13:29:

**Comment by mitselek** [comment]
``` sql
select *
from repis.kirjed k
left join import.pereregister p on p.isikukood = k.kirjekood
where k.Elukoht = ''
and p.raamatu_omavalitsus > '';

/* Affected rows: 0  Found rows: 142  Warnings: 0  Duration for 1 query: 1.328 sec. (+ 1.453 sec. network) */
```
Need 142 puuduva elukohaga persooni on ilmselt viimase aja töö tulemusel lisatud pereregistrid.

Sünkroniseerin ka need elukohad ja täiendan igaöist hooldusskripti.

**Comment by mitselek** [comment]
``` sql
CALL maintenance.update_elukoht();

/* Affected rows: 11  Found rows: 0  Warnings: 0  Duration for 1 query: 4.188 sec. */
```
Oli kokku 11 persooni, kel elukoht PR'ist toomata - ei tea, mis number see 148 oli.
Nüüd on elukohad taas sünkroonis
