### ISSUE TITLE
Päring Rahvastikuregistrisse

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/repis#14]
Valmistada ette tabel üle KÕIGI nimede, kelle andmed on kirjereal täissünnikuupäevaga, olenemata sellest kas meil on surmakuupäev teada või mitte.

**Comment by UlleKr** [comment]
@mitselek

**Comment by UlleKr** [comment]
select *
from repis.kirjed k
where length(sünd) = 10
and persoon = kirjekood

and pub_isPerson = 1


Palun saada Meelisele sel kujul nagu varasemalt oled teinud.


Kontakt Mihkel Putrinš ***@***.***>) kirjutas kuupäeval T,
23. aprill 2024 kell 13:07:

**Comment by mitselek** [comment]
https://docs.google.com/spreadsheets/d/1TVSgXyNpsceTc5IkHI5I4Q5mdf_hwOpDg4uOP0Oxn7k/edit#gid=0
