### ISSUE TITLE
PR kirjed Taranowka tabelisse

### ISSUE THREAD

**Issue by mitselek** [memoriaal/repis#15]
- Taranowka tabel - https://docs.google.com/spreadsheets/d/1oIj7A3u1OCX6sK90o4YqBGEAmBoDyxATopKCUG_wWi4/edit#gid=0
- Näidiseks Narwa tabel https://docs.google.com/spreadsheets/d/1d9_8KQAkZbUU0utmcIjJp4J1EMCjnvg2IuDfZT-7ZM0/edit#gid=0

Taranowka tabelis tuleb kõigile ridadele tuua isikuandmed vastavalt PR koodile

**Comment by mitselek** [comment]
- Uus sakk PR
  A1 = `"SELECT isikukood, isik_eesnimi, isik_perenimi, sünd, surm, raamatu_omavalitsus FROM import.pereregister WHERE isikukood IN ('"&JOIN("','",Leht1!C2:C18)&"');"`
- Uus sakk R14-16
  A1 = `"SELECT kirjekood, eesnimi, perekonnanimi, sünd, surm, sünnikoht, elukoht FROM `R14-R16` WHERE kirjekood IN  ('"&JOIN("','",Leht1!A2:A18)&"');"`
- Andmesakile uued sinised tulbad R14-16 jaoks
```
B1 = { 'R14-16'!B2:G2;
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,column(),false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,column(),false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,column(),false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,column(),false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,column(),false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,column(),false))
}
```
- Andmesakile uued rohelised tulbad PR jaoks
```
I1 = { PR!B2:F2;
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,column()-7,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,column()-7,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,column()-7,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,column()-7,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,column()-7,false))
}
```

**Comment by UlleKr** [comment]
Seal on ainult eesnimed ju? Aga las ta jääb, ma tegin praegu Antonile ja sakslastele sellise päringuga tabeli ja saatsin ära:

SELECT ss.kirjekood, ss.eesnimi, ss.perekonnanimi, ss.`sünd`, ss.kirje, pr.isikukood, pr.isik_eesnimi, pr.isik_perenimi, pr.`sünd`, pr.surm, pr.raamatu_omavalitsus
FROM import.pereregister pr
inner JOIN import.`R14-R16` as ss
ON pr.isikukood = ss.pereregister
WHERE pr.isikukood IN ('PR-0170997','PR-0008765','PR-0760871','PR-0650803','PR-0233469','PR-0488918','PR-0482253','PR-0456662','PR-0829392','PR-0843975','PR-0481500','PR-1158833','PR-0490988','PR-0317675','PR-1077109','PR-0882504','PR-1210836')
;

**Comment by mitselek** [comment]
Parandasin tulpade valemid
- B1
```
={'R14-16'!B2:G2;
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,2,false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,3,false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,4,false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,5,false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,6,false)),
    ARRAYFORMULA(VLOOKUP(A2:A,'R14-16'!A:G,7,false))}
```
- I1
```
={ PR!B2:F2;
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,2,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,3,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,4,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,5,false)),
    ARRAYFORMULA(VLOOKUP(H2:H,PR!A:F,6,false))
}
```
